const S={USERS:"Usuarios",SESSIONS:"Sessoes",CONVS:"Conversas",PART:"Participantes",MSGS:"Mensagens",REQ:"Solicitacoes",PUSH:"PushSubscriptions"};
const SHORT=1,LONG=30;
function doGet(e){try{return json(route(e.parameter||{}))}catch(err){return json({ok:false,error:err.message||"Erro interno."})}}
function route(p){switch(p.action){case"setup":return setup();case"register":return register(p);case"login":return login(p);case"logout":return logout(p);case"me":return{ok:true,user:session(p.token)};case"findUser":return findUser(p);case"createRequest":return createRequest(p);case"requests":return requests(p);case"acceptRequest":return acceptRequest(p);case"rejectRequest":return rejectRequest(p);case"conversations":return conversations(p);case"messages":return messages(p);case"sendMessage":return sendMessage(p);case"createGroup":return createGroup(p);case"pushPublicKey":return{ok:true,publicKey:PropertiesService.getScriptProperties().getProperty("VAPID_PUBLIC_KEY")||""};case"savePushSubscription":return savePush(p);default:return{ok:false,error:"Ação desconhecida."}}}
function setup(){const ss=SpreadsheetApp.openById(spreadsheetId());ensure(ss,S.USERS,["ID","Nome","Username","PasswordHash","Salt","Ativo","CriadoEm"]);ensure(ss,S.SESSIONS,["TokenHash","UserID","CriadoEm","ExpiraEm"]);ensure(ss,S.CONVS,["ID","Tipo","Nome","CriadoEm","CriadoPor"]);ensure(ss,S.PART,["ConversationID","UserID","Papel","EntrouEm"]);ensure(ss,S.MSGS,["ID","ConversationID","SenderID","Texto","CriadoEm"]);ensure(ss,S.REQ,["ID","FromUserID","ToUserID","Status","CriadoEm","RespondidoEm"]);ensure(ss,S.PUSH,["UserID","Endpoint","SubscriptionJSON","CriadoEm"]);return{ok:true,message:"Estrutura criada."}}
function register(p){const name=String(p.name||"").trim(),u=norm(p.username),pw=String(p.password||"");if(name.length<2)throw Error("Nome inválido.");if(!/^@[a-z0-9._-]{2,29}$/.test(u))throw Error("Identificador inválido.");if(pw.length<8)throw Error("A senha precisa ter pelo menos 8 caracteres.");if(userU(u))throw Error("Esse identificador já está em uso.");const salt=token(),id=next("usr",rows(sh(S.USERS)).map(r=>r[0]));sh(S.USERS).appendRow([id,name,u,hash(pw,salt),salt,true,new Date()]);return{ok:true,user:{id,name,username:u}}}
function login(p){const u=norm(p.username),pw=String(p.password||""),r=userU(u);if(!r||String(r[5])!=="true"||hash(pw,String(r[4]))!==String(r[3]))throw Error("Identificador ou senha inválidos.");const raw=token(),now=new Date(),exp=new Date(now.getTime()+(String(p.remember)==="1"?LONG:SHORT)*86400000);sh(S.SESSIONS).appendRow([sha(raw),r[0],now,exp]);return{ok:true,token:raw,expiresAt:exp.toISOString(),user:pub(r)}}
function logout(p){const h=sha(String(p.token||"")),s=sh(S.SESSIONS),d=s.getDataRange().getValues();for(let i=1;i<d.length;i++)if(String(d[i][0])===h){s.deleteRow(i+1);break}return{ok:true}}
function findUser(p){session(p.token);const r=userU(norm(p.username));if(!r||String(r[5])!=="true")throw Error("Usuário não encontrado.");return{ok:true,user:pub(r)}}
function createRequest(p){const me=session(p.token),to=String(p.targetUserId||"");if(!to||to===me.id)throw Error("Destinatário inválido.");if(!userId(to))throw Error("Usuário não encontrado.");if(pending(me.id,to)||pending(to,me.id)||between(me.id,to))throw Error("Já existe uma solicitação ou conversa.");const id=next("req",rows(sh(S.REQ)).map(r=>r[0]));sh(S.REQ).appendRow([id,me.id,to,"PENDENTE",new Date(),""]);return{ok:true}}
function requests(p){const me=session(p.token),out=[];rows(sh(S.REQ)).forEach(r=>{if(String(r[3])!=="PENDENTE")return;if(String(r[2])===me.id)out.push({id:r[0],direction:"incoming",user:pub(userId(r[1]))});if(String(r[1])===me.id)out.push({id:r[0],direction:"outgoing",user:pub(userId(r[2]))})});return{ok:true,requests:out}}
function acceptRequest(p){const me=session(p.token),r=findReq(p.requestId);if(!r||String(r[2])!==me.id||String(r[3])!=="PENDENTE")throw Error("Solicitação inválida.");const cid=createConv("private","",me.id,[String(r[1]),me.id]);statusReq(r[0],"ACEITA");return{ok:true,conversationId:cid}}
function rejectRequest(p){const me=session(p.token),r=findReq(p.requestId);if(!r||String(r[2])!==me.id||String(r[3])!=="PENDENTE")throw Error("Solicitação inválida.");statusReq(r[0],"RECUSADA");return{ok:true}}
function conversations(p){const me=session(p.token),ps=rows(sh(S.PART)),cs=rows(sh(S.CONVS)),ids=ps.filter(r=>String(r[1])===me.id).map(r=>String(r[0])),out=[];cs.forEach(c=>{const id=String(c[0]);if(!ids.includes(id))return;let title=String(c[2]||""),username="";if(String(c[1])==="private"){const oid=ps.filter(r=>String(r[0])===id&&String(r[1])!==me.id).map(r=>String(r[1]))[0],o=userId(oid);title=o?String(o[1]):"Usuário";username=o?String(o[2]):""}out.push({id,type:String(c[1]),title:title||"Grupo",username})});return{ok:true,conversations:out}}
function messages(p){const me=session(p.token),cid=String(p.conversationId||"");participant(cid,me.id);return{ok:true,messages:rows(sh(S.MSGS)).filter(r=>String(r[1])===cid).slice(-100).map(r=>{const u=userId(r[2]);return{id:r[0],userId:r[2],username:u?u[2]:"Usuário",text:r[3],createdAt:new Date(r[4]).toISOString()}})}}
function sendMessage(p){const me=session(p.token),cid=String(p.conversationId||""),text=String(p.text||"").trim();if(!text)throw Error("Mensagem vazia.");if(text.length>1000)throw Error("Mensagem muito longa.");participant(cid,me.id);const id=next("msg",rows(sh(S.MSGS)).map(r=>r[0]));sh(S.MSGS).appendRow([id,cid,me.id,text,new Date()]);return{ok:true,messageId:id}}
function createGroup(p){const me=session(p.token),name=String(p.name||"").trim();if(name.length<2||name.length>60)throw Error("Nome de grupo inválido.");let us;try{us=JSON.parse(p.usernames||"[]")}catch{throw Error("Lista inválida.")}const ids=[me.id];us.forEach(x=>{const u=userU(norm(x));if(!u)throw Error("Usuário não encontrado: "+x);if(!ids.includes(String(u[0])))ids.push(String(u[0]))});if(ids.length<2)throw Error("Adicione pelo menos outra pessoa.");return{ok:true,conversationId:createConv("group",name,me.id,ids)}}
function savePush(p){const me=session(p.token),sub=String(p.subscription||""),o=JSON.parse(sub),ep=String(o.endpoint||"");if(!ep)throw Error("Subscription inválida.");const s=sh(S.PUSH),d=rows(s);for(let i=0;i<d.length;i++)if(String(d[i][0])===me.id&&String(d[i][1])===ep){s.getRange(i+2,3,1,2).setValues([[sub,new Date()]]);return{ok:true}}s.appendRow([me.id,ep,sub,new Date()]);return{ok:true}}
function spreadsheetId(){const x=PropertiesService.getScriptProperties().getProperty("SPREADSHEET_ID");if(!x)throw Error("Defina SPREADSHEET_ID nas propriedades do script.");return x}
function sh(n){const s=SpreadsheetApp.openById(spreadsheetId()).getSheetByName(n);if(!s)throw Error("Aba não encontrada: "+n);return s}
function rows(s){return s.getLastRow()<2?[]:s.getRange(2,1,s.getLastRow()-1,s.getLastColumn()).getValues()}
function ensure(ss,n,h){let s=ss.getSheetByName(n);if(!s)s=ss.insertSheet(n);if(s.getLastRow()===0){s.appendRow(h);s.setFrozenRows(1)}}
function session(t){if(!t)throw Error("Sessão ausente.");const h=sha(String(t)),d=rows(sh(S.SESSIONS)),now=new Date();for(const r of d)if(String(r[0])===h){if(new Date(r[3])<=now)throw Error("Sessão expirada.");const u=userId(r[1]);if(!u||String(u[5])!=="true")throw Error("Usuário inválido.");return pub(u)}throw Error("Sessão inválida.")}
function participant(cid,uid){if(!rows(sh(S.PART)).some(r=>String(r[0])===cid&&String(r[1])===uid))throw Error("Você não participa desta conversa.")}
function createConv(type,name,creator,ids){const lock=LockService.getScriptLock();lock.waitLock(10000);try{const id=next("conv",rows(sh(S.CONVS)).map(r=>r[0]));sh(S.CONVS).appendRow([id,type,name,new Date(),creator]);ids.forEach((u,i)=>sh(S.PART).appendRow([id,u,i===0?"ADMIN":"MEMBRO",new Date()]));return id}finally{lock.releaseLock()}}
function between(a,b){const ps=rows(sh(S.PART)),cs=rows(sh(S.CONVS));return cs.some(c=>String(c[1])==="private"&&ps.filter(r=>String(r[0])===String(c[0])).map(r=>String(r[1])).sort().join("|")===[a,b].sort().join("|"))}
function userU(u){return rows(sh(S.USERS)).find(r=>String(r[2]).toLowerCase()===u.toLowerCase())||null}
function userId(id){return rows(sh(S.USERS)).find(r=>String(r[0])===String(id))||null}
function pub(r){return{id:String(r[0]),name:String(r[1]),username:String(r[2])}}
function pending(a,b){return rows(sh(S.REQ)).some(r=>String(r[1])===a&&String(r[2])===b&&String(r[3])==="PENDENTE")}
function findReq(id){return rows(sh(S.REQ)).find(r=>String(r[0])===String(id))||null}
function statusReq(id,status){const s=sh(S.REQ),d=s.getDataRange().getValues();for(let i=1;i<d.length;i++)if(String(d[i][0])===String(id)){s.getRange(i+1,4,1,2).setValues([[status,new Date()]]);return}}
function norm(v){v=String(v||"").trim().toLowerCase();return v.startsWith("@")?v:"@"+v}
function next(prefix,arr){let m=0;arr.forEach(x=>{const z=String(x).match(new RegExp("^"+prefix+"_(\\d+)$"));if(z)m=Math.max(m,Number(z[1]))});return prefix+"_"+String(m+1).padStart(6,"0")}
function token(){return Utilities.getUuid().replace(/-/g,"")+Utilities.getUuid().replace(/-/g,"")}
function sha(t){return Utilities.computeDigest(Utilities.DigestAlgorithm.SHA_256,t,Utilities.Charset.UTF_8).map(b=>(b<0?b+256:b).toString(16).padStart(2,"0")).join("")}
function hash(p,s){return sha(s+":"+p)}
function json(o){return ContentService.createTextOutput(JSON.stringify(o)).setMimeType(ContentService.MimeType.JSON)}